theme: minima # Jekyll theme applied globally
# Site settings
title: "Junkai's website"
description: "Man! What can I say?"
#log: /assets/imgs/We.png
url: "https://jyang635.github.io"
# Custom Navigation Links
nav:
  - name: "Home"
    url: "/"
  - name: "About"
    url: "/about"
  - name: "Projects"
    url: "/projects"
  - name: "Blog"
    url: "/blog"
  - name: "Contact"
    url: "/contact"

