theme: minima # Jekyll theme applied globally
# Site settings
title: "Junkai's website"
description: "Man! What can I say?"
#log: /assets/imgs/We.png
url: "https://jyang635.github.io"
author:
  name: "Your Name"
  email: "your-email@example.com"
  url: "https://yourwebsite.com"
social_links:
  twitter: your_twitter_username
  github: your_github_username
  linkedin: your_linkedin_username
