theme: minima # Jekyll theme applied globally
# Site settings
title: "My Data Science Portfolio"
description: "Projects, blog posts, and insights by a data scientist"
url: "https://jyang635.github.io"

# Social media contact info
social:
  email: "your.email@example.com"
  github: "https://github.com/<username>"
  linkedin: "https://linkedin.com/in/your-profile"
  twitter: "https://twitter.com/your-profile"


