theme: minima # Jekyll theme applied globally
# Site settings
title: "Junkai's website"
description: "Projects, blog posts, and insights by a data scientist"
url: "https://jyang635.github.io"
author: 
  name: "Junkai Yang"
  email: "your.email@example.com"

